use_frameworks!

source 'https://github.com/answerfan/AnswerfanSpecs.git'

target 'TauntStringWrapper_Example' do
  pod 'TauntStringWrapper', :path => '../'

  target 'TauntStringWrapper_Tests' do
    inherit! :search_paths

    
  end
end
